store_path: /var/lib/grootfs/btrfs
driver: btrfs
btrfs_bin: /bin/btrfs
tardis_bin: /usr/local/bin/tardis
drax_bin: /usr/local/bin/drax
newuidmap_bin: /usr/local/bin/newuidmap
newgidmap_bin: /usr/local/bin/newgidmap
log_level: debug
log_file:
metron_endpoint: 127.0.0.1:1234
clean:
  cache_size: 1048576
  ignore_images: []
create:
  insecure_registries: []
  with_clean: false
  without_mount: false
